// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rehber.Api.Data;

namespace Rehber.Api.Migrations
{
    [DbContext(typeof(RehberContext))]
    [Migration("20211228113539_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Rehber.Entities.Concrete.Kullanıcı", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GüncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OluşturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarası")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanıcılar");
                });

            modelBuilder.Entity("Rehber.Entities.Concrete.TelefonRehberi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GüncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullanıcıId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OluşturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonNumarası")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullanıcıId");

                    b.ToTable("TelefonRehberleri");
                });

            modelBuilder.Entity("Rehber.Entities.Concrete.TelefonRehberi", b =>
                {
                    b.HasOne("Rehber.Entities.Concrete.Kullanıcı", "Kullanıcı")
                        .WithMany("TelefonRehberleri")
                        .HasForeignKey("KullanıcıId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("Rehber.Entities.Concrete.Kullanıcı", b =>
                {
                    b.Navigation("TelefonRehberleri");
                });
#pragma warning restore 612, 618
        }
    }
}
